### ISSUE TITLE
Criar RoadMap de Papeis

### ISSUE THREAD

**Issue by mateusvroriz** [fga-eps-mds/2018.2-CarDefense#21]
## Descrição da Tarefa
É necessário que a equipe de desenvolvedores de MDS elaborem o Protótipo de Baixa Fidelidade

## Critérios de Aceitação
- [x] Roadmap de Scrum Master
- [x] Roadmap de Product Owner[PO]/Engenheiro do Produto
- [x] Roadmap de Arquiteto
- [x] Roadmap de DevOps

**Comment by victorcmoura** [comment]
Documento que pode ser útil pra vocês:
https://github.com/fga-eps-mds/A-Disciplina/blob/master/Devops/roadmap-devops.md
